# Generated by Django 5.2.3 on 2025-07-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField()),
                ('height', models.FloatField()),
                ('height_limit', models.FloatField()),
                ('home_distance', models.FloatField()),
                ('horizontal_speed', models.FloatField()),
                ('vertical_speed', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('gear', models.IntegerField()),
                ('is_near_area_limit', models.BooleanField()),
                ('is_near_height_limit', models.BooleanField()),
                ('rc_lost_action', models.IntegerField()),
                ('rid_state', models.BooleanField()),
                ('rth_altitude', models.FloatField()),
                ('storage_total', models.BigIntegerField()),
                ('storage_used', models.BigIntegerField()),
                ('total_flight_distance', models.FloatField()),
                ('total_flight_sorties', models.IntegerField()),
                ('total_flight_time', models.FloatField()),
                ('track_id', models.CharField(blank=True, max_length=255)),
                ('classification', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
