# Generated by Django 5.2.3 on 2025-07-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droneData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronedata',
            name='drone_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
